require("user.core.autocommands")
require("user.core.options")
require("user.core.keymaps")
require("user.core.plugins")

require("user.plugins.cmp")
require("user.lsp.mason")
require("user.lsp.lspsaga")
require("user.lsp.null-ls")
require("user.dap.config")